<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="10.0.3" />
    <PackageReference Include="MudBlazor" Version="9.*" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NorthwindAspire.ServiceDefaults\NorthwindAspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\NorthwindAspire.Shared\NorthwindAspire.Shared.csproj" />
    <ProjectReference Include="..\NorthwindAspire.Backend\NorthwindAspire.Backend.csproj" />
  </ItemGroup>
</Project>